services:
  site1:
    build:
      context: ./site1
    container_name: site1
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - site1
  
  site2:
    build:
      context: ./site2
    container_name: site2
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - site2



networks:
  site1:
    driver: bridge
  site2:
    driver: bridge
