controller:
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: ClusterIP
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
