FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html script.js style.css /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]