FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/site2.conf
COPY index.html styles.css /usr/share/nginx/html/
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY images /usr/share/nginx/html/images

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]